# Generated by Django 5.2.4 on 2025-10-07 14:04

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0002_alter_product_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookorderitem",
            name="downloaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="book_file",
            field=models.FileField(blank=True, null=True, upload_to="books/"),
        ),
        migrations.AlterField(
            model_name="bookorder",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bookorder",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bookorder",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="bookorderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="bookpreview",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="sermoncontent",
            name="text_body",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
