# Generated by Django 5.2.4 on 2026-01-31 14:52

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0003_bookorderitem_downloaded_product_book_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pesapal_tracking_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status_code", models.CharField(max_length=10)),
                ("status_description", models.TextField()),
                ("ipn_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="bookorder",
            options={"ordering": ("-created",)},
        ),
        migrations.RemoveField(
            model_name="bookorder",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="bookorder",
            name="shipping_fee",
        ),
        migrations.AddField(
            model_name="bookorder",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="city",
            field=models.CharField(
                blank=True, default="Kampala", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="country",
            field=models.CharField(
                blank=True, default="Uganda", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="payment_method",
            field=models.CharField(
                choices=[("pesapal", "PesaPal")], default="pesapal", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="pesapal_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="pesapal_redirect_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="pesapal_tracking_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookorderitem",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookorder",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookorder",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("collected", "Paid & Ready"),
                    ("failed", "Payment Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscribermessage",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AddIndex(
            model_name="bookorder",
            index=models.Index(fields=["tx_ref"], name="ecomapp_boo_tx_ref_c35001_idx"),
        ),
        migrations.AddIndex(
            model_name="bookorder",
            index=models.Index(fields=["email"], name="ecomapp_boo_email_6348dc_idx"),
        ),
        migrations.AddIndex(
            model_name="bookorder",
            index=models.Index(fields=["status"], name="ecomapp_boo_status_d1efcb_idx"),
        ),
        migrations.AddIndex(
            model_name="bookorder",
            index=models.Index(
                fields=["payment_status"], name="ecomapp_boo_payment_a51cda_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_logs",
                to="ecomapp.bookorder",
            ),
        ),
    ]
